spring:
  application:
    name: ecommerce-api

  config:
    import: file:env.yml

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: true
