CREATE TABLE token
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token      VARCHAR(255),
    token_type VARCHAR(255),
    revoked    BOOLEAN                                  NOT NULL,
    expired    BOOLEAN                                  NOT NULL,
    user_id    BIGINT,
    CONSTRAINT pk_token PRIMARY KEY (id)
);

ALTER TABLE token
    ADD CONSTRAINT uc_token_token UNIQUE (token);

ALTER TABLE token
    ADD CONSTRAINT FK_TOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);